.TH "lib/include Directory Reference" 3 "Thu May 10 2018" "Version 0.3.2-0" "libcmdparse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcmdparse\&.h\fP"
.br
.RI "\fIinterface to parse command line arguments/options \fP"
.in -1c
