.TH "lib/src Directory Reference" 3 "Sat Mar 17 2018" "Version 0.3.2-0" "liboptparse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBoptions_parsing\&.cpp\fP"
.br
.RI "\fIparse command line arguments/options \fP"
.in -1c
