.TH "cli::option_language_error" 3 "Thu May 10 2018" "Version 0.3.2-0" "libcmdparse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cli::option_language_error \- thrown when options declared  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdparse\&.h>\fP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoption_language_error\fP (std::string &&msg)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexceptoverride"
.br
.in -1c
.SH "Detailed Description"
.PP 
thrown when options declared 

.SH "Author"
.PP 
Generated automatically by Doxygen for libcmdparse from the source code\&.
