.TH "opt_parser" 3 "Thu May 10 2018" "Version 0.3.2-0" "libcmdparse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opt_parser \- class controlling option declaration and parsing  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdparse\&.h>\fP
.SH "Detailed Description"
.PP 
class controlling option declaration and parsing 

.SH "Author"
.PP 
Generated automatically by Doxygen for libcmdparse from the source code\&.
