.TH "lib/src/options_parsing.cpp" 3 "Sat Mar 17 2018" "Version 0.3.2-0" "liboptparse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/src/options_parsing.cpp \- parse command line arguments/options  

.SH SYNOPSIS
.br
.PP
\fC#include 'options_parsing\&.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <cctype>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDT_STATE\fP { \fBSTART\fP, \fBLDIGIT\fP, \fBRDIGIT\fP, \fBDOT\fP, \fBEND\fP }"
.br
.ti -1c
.RI "enum \fBOption_State\fP { \fBMOD\fP, \fBHANDLES\fP, \fBEQ\fP, \fBARG\fP, \fBARGLIST\fP, \fBARGLIST_END\fP, \fBDONE\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
parse command line arguments/options 


.PP
\fBAuthor:\fP
.RS 4
Adam Marshall (ih8celery) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for liboptparse from the source code\&.
