.TH "util::config_constants" 3 "Sun Mar 11 2018" "Version 0.3.0" "liboptparse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util::config_constants \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbsd_opt_t\fP"
.br
.ti -1c
.RI "struct \fBcase_sensitive_t\fP"
.br
.ti -1c
.RI "struct \fBerror_if_unknown_t\fP"
.br
.ti -1c
.RI "struct \fBmerged_opt_t\fP"
.br
.ti -1c
.RI "struct \fBsubcommand_t\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBcase_sensitive_t\fP \fBcase_sensitive\fP = \fBcase_sensitive_t\fP()"
.br
.ti -1c
.RI "const \fBbsd_opt_t\fP \fBbsd_opt\fP = \fBbsd_opt_t\fP()"
.br
.ti -1c
.RI "const \fBmerged_opt_t\fP \fBmerged_opt\fP = \fBmerged_opt_t\fP()"
.br
.ti -1c
.RI "const \fBerror_if_unknown_t\fP \fBerror_unknown\fP = \fBerror_if_unknown_t\fP()"
.br
.ti -1c
.RI "const \fBsubcommand_t\fP \fBsub\fP = \fBsubcommand_t\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBbsd_opt_t\fP util::config_constants::bsd_opt = \fBbsd_opt_t\fP()"

.SS "const \fBcase_sensitive_t\fP util::config_constants::case_sensitive = \fBcase_sensitive_t\fP()"

.SS "const \fBerror_if_unknown_t\fP util::config_constants::error_unknown = \fBerror_if_unknown_t\fP()"

.SS "const \fBmerged_opt_t\fP util::config_constants::merged_opt = \fBmerged_opt_t\fP()"

.SS "const \fBsubcommand_t\fP util::config_constants::sub = \fBsubcommand_t\fP()"

.SH "Author"
.PP 
Generated automatically by Doxygen for liboptparse from the source code\&.
