.TH "util::option_t" 3 "Sat Mar 17 2018" "Version 0.3.2-0" "liboptparse" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util::option_t \- collects the properties and identity of an option  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <options_parsing\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoption_t\fP ()"
.br
.RI "\fIdefault constructor for \fBoption_t\fP \fP"
.ti -1c
.RI "bool \fBcompatible\fP (const \fBoption_t\fP &opt) const "
.br
.RI "\fItests whether options are similar enough to be used interchangeably \fP"
.ti -1c
.RI "bool \fBoperator==\fP (const \fBoption_t\fP &opt) const "
.br
.RI "\fIcompares names of options \fP"
.ti -1c
.RI "bool \fBoperator<\fP (const \fBoption_t\fP &opt) const "
.br
.RI "\fIcompares names of options \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMod_Prop\fP \fBmod\fP"
.br
.ti -1c
.RI "std::string \fBmod_arg\fP"
.br
.ti -1c
.RI "\fBNum_Prop\fP \fBnumber\fP"
.br
.ti -1c
.RI "\fBAssign_Prop\fP \fBassignment\fP"
.br
.ti -1c
.RI "\fBCollect_Prop\fP \fBcollection\fP"
.br
.ti -1c
.RI "\fBData_Prop\fP \fBdata_type\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
collects the properties and identity of an option 

.SH "Author"
.PP 
Generated automatically by Doxygen for liboptparse from the source code\&.
